### ISSUE TITLE
Missing DYMOPrinting.dll on DYMO Connect 1.3.2.18

### ISSUE THREAD

**Issue by joeadcock** [dymosoftware/dymo-connect-framework#18]
I am attempting to update from DLS to DYMO Connect 1.3.2.18.  I am getting an exception `Could not load file or assembly 'DYMOPrinting.dll' or one of its dependencies. The specified module could not be found.`  I can confirm that there is a DYMOPrinting.dll and DYMOPrinting_x64.dll in C:\Program Files (x86)\DYMO\DYMO Connect.  I was not able to find the download from the "DYMO Connect Software" link in the README, so I may have downloaded an older version of DYMO connect.  I downloaded 1.3.2.18 using the link on https://www.dymo.com/en_US/online-support-compatibility-chart (https://download.dymo.com/dymo/Software/DCDSetup1.3.2.18.exe).

```
{"message":"An error has occurred.","exceptionMessage":"The type initializer for 'DYMO.LabelAPI.Windows.Printers.DYMOPrinting' threw an exception.","exceptionType":"System.TypeInitializationException","stackTrace":"   at DYMO.LabelAPI.Windows.Printers.DYMOPrinting.EndPrintJob()
   at DYMO.LabelAPI.Windows.BasePrintDecorator.Print(BaseLegacyPrinterCommunication communication, IEnumerable`1 labels, PrintParameters printParam, IResolution resolution)
   at DYMO.LabelAPI.BaseLegacyPrinterCommunication.Print(IEnumerable`1 labels, PrintParameters printParam, IResolution resolution)
   at DYMO.LabelAPI.Printer.Print(IEnumerable`1 labels, PrintParameters printParams)
   at DymoSDK.Implementations.DymoPrinter.PrintLabel(IEnumerable`1 labels, String printerName, Int32 copies, Boolean collate, Boolean mirror, Int32 rollSelected, Boolean chainMarks, Boolean barcodeGraphsQuality)
   at DYMOWebApi.Windows.Controllers.DymoDLSSDKController.PrintLabel(FormDataCollection formDataCollection)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()","innerException":{"message":"An error has occurred.","exceptionMessage":"Could not load file or assembly 'DYMOPrinting.dll' or one of its dependencies. The specified module could not be found.","exceptionType":"System.IO.FileNotFoundException","stackTrace":"   at DYMO.LabelAPI.Windows.Printers.DYMOPrinting..cctor()"}}
```

**Comment by joeadcock** [comment]
This appears to have been a problem with the Windows 10 evaluation image I was using to test with, it is working on a different Windows 10 instance.
