### ISSUE TITLE
.NET core error

### ISSUE THREAD

**Issue by jlewin** [dymosoftware/dymo-connect-framework#5]
When attempting to build a simple .NET core console app and after adding the latest Nuget package for `DYMO.Connect.SDK v1.3.1.115`  the runtime error depicted below is thrown on load.

Given that the requirements on the Nuget package show .net standard 2, it seemed likely that it would run on .net core. Is this error expected or is it a product bug or a misconfig on my part?

![image](https://user-images.githubusercontent.com/175113/76150106-94070580-605b-11ea-8ec4-04d11307a400.png)

>Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'DYMO.CrossPlatform.Common, Version=1.3.1.115, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'DYMO.CrossPlatform.Common, Version=1.3.1.115, Culture=neutral, PublicKeyToken=null'
   at DymoPrintServerCore.DymoPrintServer..ctor()
   at DymoPrintServerCore.Program.Main(String[] args) in C:\Data\Source\QuickTools\DymoPrintServerCore\Program.cs:line 9

**Comment by jlewin** [comment]
After creating a new .NET v4.7.2 project, the same code runs without error

**Comment by dymosoftware** [comment]
Hi @jlewin , this is an expected error, since some of our platform libraries are not fully compatible with .Net Core. We keep it in mind for further releases.

**Comment by jlewin** [comment]
That's unfortunate. I was hoping to host my assembly in a .NET Core worker service so I could remotely invoke print jobs. I spent the bulk of the weekend trying to work around this limitation and finally had success falling back to .NET v4.7.x and using NancyFx to host the service. Seems to run great but took significantly more time than the worker service route would have.

Thanks for the update and hopefully .NET Core can be a priority in the future.

**Comment by githubsamurai** [comment]
Does the new SDK support .NET Core and/or  .NET 5 and above?

**Comment by doughayman2** [comment]
Any solutions on this yet?  I'm developing VB.net apps in Visual Studio 2022 (Net 6.0; Net Framework 4.8+), and get the following error when attempting to execute the following SDK code:

Imports DymoSDK.Implementations
Imports DymoSDK.Interfaces
DymoSDK.App.Init()
        Dim dymoSDKPrinter = DymoPrinter.Instance

        Dim fullpath As String = System.IO.Path.GetFullPath("d:\label.label")
        Dim dymoSDKLabel = DymoLabel.Instance
        dymoSDKLabel.LoadLabelFromFilePath(fullpath)

        Dim LabelTextObject1 As DymoSDK.Interfaces.ILabelObject
        LabelTextObject1 = dymoSDKLabel.GetLabelObject("NameOfLabel")
        dymoSDKLabel.UpdateLabelObject(LabelTextObject1, "ValueOfLabel")

        If dymoSDKPrinter.PrintLabel(dymoSDKLabel, ItemId.Text, 1, False, False, 0, False, False) Then
            MsgBox("Printed !", vbInformation)
        End If

****"System.IO.FileNotFoundException: 'Could not load file or assembly 'DYMO.CrossPlatform.Common, Version=1.4.3.37, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'**"**

I've loaded the following packages:

Dymo.Connect.SDK V1.4.3.37
NetStandard.Library V2.0.3
SkiaSharp V2.88.3
SkiaSharp.Views V2.88.3

The following link implies that my environment is supported by the Dymo SDK:

https://www.nuget.org/packages/DYMO.Connect.SDK/#supportedframeworks-body-tab

Anybody have any ideas on this?

Thanks in advance.

**Comment by JLOrdaz** [comment]
I have the same issue, please help!!!

**Comment by Eli1995** [comment]
> Any solutions on this yet? I'm developing VB.net apps in Visual Studio 2022 (Net 6.0; Net Framework 4.8+), and get the following error when attempting to execute the following SDK code:
> 
> Imports DymoSDK.Implementations Imports DymoSDK.Interfaces DymoSDK.App.Init() Dim dymoSDKPrinter = DymoPrinter.Instance
> 
> ```
>     Dim fullpath As String = System.IO.Path.GetFullPath("d:\label.label")
>     Dim dymoSDKLabel = DymoLabel.Instance
>     dymoSDKLabel.LoadLabelFromFilePath(fullpath)
> 
>     Dim LabelTextObject1 As DymoSDK.Interfaces.ILabelObject
>     LabelTextObject1 = dymoSDKLabel.GetLabelObject("NameOfLabel")
>     dymoSDKLabel.UpdateLabelObject(LabelTextObject1, "ValueOfLabel")
> 
>     If dymoSDKPrinter.PrintLabel(dymoSDKLabel, ItemId.Text, 1, False, False, 0, False, False) Then
>         MsgBox("Printed !", vbInformation)
>     End If
> ```
> 
> ****"System.IO.FileNotFoundException: 'Could not load file or assembly 'DYMO.CrossPlatform.Common, Version=1.4.3.37, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'**"**
> 
> I've loaded the following packages:
> 
> Dymo.Connect.SDK V1.4.3.37 NetStandard.Library V2.0.3 SkiaSharp V2.88.3 SkiaSharp.Views V2.88.3
> 
> The following link implies that my environment is supported by the Dymo SDK:
> 
> https://www.nuget.org/packages/DYMO.Connect.SDK/#supportedframeworks-body-tab
> 
> Anybody have any ideas on this?
> 
> Thanks in advance.

I have the same problem..have you solved?

**Comment by beanbabyclothes** [comment]
Same issue here.
The amount of time lost with this library problems and its monstrous dependencies, i wish i knew.
